spring.application.name=auth

# DB 설정
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://${DB_URL:localhost}:3306/community?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

# JWT 설정
jwt.secret=${JWT_SECRET}
jwt.token-validity-in-seconds=1800
jwt.refresh-token-validity-in-seconds=604800